config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   get  'home/about'
   get  'home/index'
  root 'friends#index'
 
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end


  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
    @friend
  end
  
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized " if @friend.nil? 
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:fastname, :lastname, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < FriendsController 
  def index
  end
  def about
  end
  def _header
    @friend = Friend.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="">
 
    <%= form.text_field :fastname,class:"form-control", placeholder:"First Name" %>
  </div >
  <br>
  <div class="field form-group">
   
    <%= form.text_field :lastname,class:"form-control", placeholder:"Last Name" %>
  </div>
  <br>
  <div class="field form-group">
   
    <%= form.text_field :email,class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="field form-group">

    <%= form.text_field :phone,class:"form-control", placeholder:"Phone" %>
  </div>
  <br>
  <div class="field form-group">
 
    <%= form.text_field :twitter,class:"form-control", placeholder:"Twitter" %>
  </div>
  <div class="field form-group">
 
    <%= form.number_field :user_id, value:current_user.id, placeholder:"user_id",class:"form-control", type:"hidden"%>
  </div>
  <br>
 
  <div class="mb-3">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
      <div class="jumbotron bg-secondary text-white text-center">
        <h1 class="display-4"><%= friend.fastname %> <%= friend.lastname %></h1>
        <p class="lead">Email: <%= friend.email %></p>
        <p class="lead">Phone: <%= friend.phone %></p>
        <p class="lead">Twitter: <%= friend.twitter %></p>
        <hr class="my-4">
      </div>
  

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend  %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<div class = "container">
<table class="table table-striped table table-hover table table-bordered table align-middle">
  <thead  class="table-dark">
  <tr class="table-active">
      <th>Fast Name</th>
      <th>Last Name</th> 
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>Details</th>

    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% @friends.each do |friend| %>
      <% if friend.user_id ==current_user.id%>
      <tr >
        <td><%= friend.fastname %></td>
        <td><%= friend.lastname %></td>
         <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
           <td><%= friend.twitter %></td>
        <td><%= link_to "More", friend , class:"btn btn-secondary"%>  </td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New friend", new_friend_path, class:"btn btn-dark" %>
</div>

<% else %>

 <div class="container d-flex justify-content-center align-items-center">
            <h1 class="position-relative">Home Page</h1>
        </div>


<%end%>

app/views/friends/new.html.erb
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path , class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="text-center"style="margin-50px">
<%= render @friend %>
</div>

<div class= " text-center ">
  <%= link_to "Edit this friend", edit_friend_path(@friend) , class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path , class:"btn btn-secondary"%>
  <br>
  </br>
  <%= button_to "Destroy this friend", @friend, method: :delete ,data:{ confirm: "Are you sure?" },class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar bg-dark border-bottom border-body"data-bs-theme="dark">
  <div class="container-fluid">
  <%=link_to 'Friend App' , root_path , class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <%= link_to 'About Us' ,  home_about_path , class: "nav-link " %> 
      <%if user_signed_in?%>

      </li>
      <li class="nav-item">
      <%= link_to 'Show Friends' ,  friends_path , class: "nav-link " %> 
    </li>
      <li class="nav-item">
      <%= link_to 'Add Friends' ,  new_friend_path , class: "nav-link " %> 
    </li>
        <li class="nav-item">
  <%= link_to 'Edit Profile' ,    edit_user_registration_path , class: "nav-link " %> 
</li>
<li class="nav-item">
<form action="<%= destroy_user_session_path %>" method="delete" class="d-inline">
  <%= hidden_field_tag :_method, :delete %>
  <%= button_tag "Sign out", type: "submit", class: "btn btn-dark nav-link", data: { confirm: "Are you sure?" } %>
</form>
</li>
<%else%>

 <li class="nav-item">
      <%= link_to 'Sign Up' ,    new_user_registration_path , class: "nav-link " %> 
    </li>
    <li class="nav-item">
    <%= link_to 'Sign in' ,    new_user_session_path , class: "nav-link " %> 
  </li>
  <%end%>
    
   </ul>
   <form class="d-flex" role="search">
   <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
   <%=link_to 'Search' , @friend , class:"navbar-brand"%>

 </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container d-flex justify-content-center align-items-center">
<h1 class="position-relative">About Us</h1>
</div>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong> <%=notice%> </strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%=render "home/header" %>
    <br></br>
 
    <div class="container">
    <div class="row justify-content-center">
    <div class="col-md-8">
    <%if notice %>
    <%= render "layouts/alert"%>
    <%end%>
    <%= yield %>
    </div>
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>